### ISSUE TITLE
Error message when running any `pscale` command

### ISSUE THREAD

**Issue by traviswimer** [planetscale/setup-pscale-action#8]
I have a workflow setup similar to this:

```yaml
jobs:
  ps_job:
    runs-on: ubuntu-latest

    steps:
      - name: Setup pscale
        uses: planetscale/setup-pscale-action@v1

      - name: Run my script
        working-directory: ./scripts
        run: bash ./my_script.sh
        env:
          PLANETSCALE_SERVICE_TOKEN_ID: ${{ secrets.PLANETSCALE_SERVICE_TOKEN_ID }}
          PLANETSCALE_SERVICE_TOKEN: ${{ secrets.PLANETSCALE_SERVICE_TOKEN }}
```

Then anytime I use a `pscale` command inside `myscript.sh`, I get the following error message:

```shell
Updater error: skipping update, error: open /home/runner/.config/planetscale/state.yml: no such file or directory
```
I was able to prevent the error by creating `state.yml` before running `pscale`:

```shell
mkdir -p "/home/runner/.config/planetscale" && touch "/home/runner/.config/planetscale/state.yml"
```
This error was a problem for me because although the commands would run, they did not return the expected output.
